language: rust
sudo: false
rust:
  - beta
  - nightly
matrix:
  include:
    rust: nightly
    env:
      - FEATURES="pattern"
script: |
  cargo build --verbose --features "${FEATURES}"
  cargo test --verbose --features "${FEATURES}"
