language: rust
sudo: false
rust:
  - nightly
env:
  matrix:
  - FEATURES=""
  - FEATURES="unstable"
script: |
  cargo build --verbose --features "${FEATURES}"
  cargo test --verbose --features "${FEATURES}"
