[package]
name = "jetscii"
version = "0.3.1"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

description = "A tiny library to efficiently search strings for substrings or sets of ASCII characters."
readme = "README.md"
keywords = ["string", "ascii", "search", "substring"]

homepage = "https://github.com/shepmaster/jetscii"
repository = "https://github.com/shepmaster/jetscii"
documentation = "https://shepmaster.github.io/jetscii/"

license = "MIT"

[features]
benchmarks = []
pattern = []
unstable = []

[dev-dependencies]
quickcheck = "0.3"
libc = "0.2"
rand = "0.3"
lazy_static = "1.0.0"
