[package]
name = "jetscii"
version = "0.4.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

description = "A tiny library to efficiently search strings and byte slices for sets of ASCII characters or bytes."
readme = "README.md"
keywords = ["string", "bytes", "ascii", "search"]

homepage = "https://github.com/shepmaster/jetscii"
repository = "https://github.com/shepmaster/jetscii"
documentation = "https://shepmaster.github.io/jetscii/"

license = "MIT"

[features]
benchmarks = []
pattern = []

[dev-dependencies]
quickcheck = "0.3"
libc = "0.2"
rand = "0.3"
lazy_static = "1.0.0"
